trigger:
- master
- '*'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    curl $BEDROCK_BUILD_SCRIPT > build.sh
    chmod +x ./build.sh
  displayName: Download script
  env:
    BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

- bash: |
    . build.sh --source-only
    verify_access_token
    init
    helm init
    get_os
    get_fab_version
    download_fab
    git_connect
    
    if ! git checkout $BRANCH_NAME; then
      git checkout -b $BRANCH_NAME
    fi
    pwd
    echo "access token = $ACCESS_TOKEN"
    # cd hello-rings-cluster
    fab set --subcomponent hello-rings buildId=44444
    git add -A
    git config --global user.email "you@example.com"
    git config --global user.name "ROBOT"
    git commit -m "Fab setting buildId"
    git push https://$ACCESS_TOKEN@github.com/bnookala/hello-rings-cluster origin $BRANCH_NAME
  displayName: Fab set version
  env:
    BRANCH_NAME: $(Build.SourceBranchName)
    ACCESS_TOKEN_SECRET: $(ACCESS_TOKEN)
    REPO: "https://github.com/bnookala/hello-rings-cluster"