trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    curl $BEDROCK_BUILD_SCRIPT > build.sh
    chmod +x ./build.sh
  displayName: Download script
  env:
    BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

- bash: |
    . build.sh --source-only

    # Initialization
    verify_access_token
    init
    helm init
    get_os

    # Fabrikate
    get_fab_version
    download_fab

    # Clone HLD repo
    git_connect

    fab add hello-rings --source https://github.com/bnookala/hello-rings-hld

    echo "GIT STATUS"
    git status

    echo "GIT ADD"
    git add -A

    # Set git identity
    git config user.email "admin@azuredevops.com"
    git config user.name "Automated Account"

    echo "GIT COMMIT"
    git commit -m "$COMMIT_MESSAGE"

    echo "GIT PUSH"
    git_push
  displayName: Fab Add HLD