subcomponents:
  hello-rings-featurea:
    config:
      author: GitHub
      branchName: featurea
      buildDate: "2019-06-25T09:08:50.3790219Z"
      buildId: "4322"
      commitId: b11b2ee250b44d25cf5e86a8b35e858af6852a9f
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurea-4322
  hello-rings-featurez:
    config:
      author: GitHub
      branchName: featurez
      buildDate: "2019-06-25T15:04:03.5413203Z"
      buildId: "4478"
      commitId: ecc42ec8cc1fb0364e9694991cf5d49b44ee9eee
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurez-4478
  hello-rings-master:
    config:
      author: Samiya Akhtar
      branchName: master
      buildDate: "2019-06-25T08:45:08.864258Z"
      buildId: "4312"
      commitId: b08fc564fa7aed09dbd46241b7a0d35e978ee0bb
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-4312
