subcomponents:
  hello-rings:
    subcomponents:
      hello-rings-master:
        config:
          buildId: "4588"
      hello-rings-pr_hello-rings-featureydawgie-4743:
        config:
          buildId: "4756"
