subcomponents:
  hello-rings:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: featureA-3709
  hello-rings-master:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-3717
