subcomponents:
  hello-rings-featurea:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurea-3955
  hello-rings-featureb:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featureb-3951
  hello-rings-featurec:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurec-4022
  hello-rings-master:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-3950
