subcomponents:
  featureA:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: featureA-3719
  hello-rings-master:
    config:
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-3723
