subcomponents:
  hello-rings:
    subcomponents:
      hello-rings-master:
        config:
          buildId: "4551"
      hello-rings-pr_hello-rings-a-4558:
        config:
          buildId: "4559"
