subcomponents:
  hello-rings-featureydawgie:
    config:
      branchName: featureydawgie
      buildDate: "2019-07-09T20:32:45.3370753Z"
      buildId: "4890"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featureydawgie-4890
